### ISSUE TITLE
Release 2 CAD Assembly?

### ISSUE THREAD

**Issue by CCS86** [Annex-Engineering/Masherbrum-K1#1]
Hi guys, is a Release 2 CAD Assembly on the way?

I am new to this project and want to check out some of the details. Thanks!

**Comment by Annex-Engineering** [comment]
we do not publish cad unless the "product" is in a full released state. this prevents fragmentation, etc in our user base.

files will ship with the full "Release 2" flag. There are a few internal issues holding things up at this time.

In the mean time, we suggest using the edrawings files.
