### ISSUE TITLE
electronics_box_side_panel_decorative_x3_rev2.DXF has detail smaller than 1/8 aka 0.125 inch in size

### ISSUE THREAD

**Issue by richardk3nt** [Annex-Engineering/Masherbrum-K1#2]
After I uploaded the electronics_box_side_panel_decorative_x3_rev2.DXF to sendcutsend to be cut from 1/8" / 3.2mm ABS the provided the following feedback.  I asked them to delete the feature from the drawing.  I bring this up as it holds up the order and they seem slow to respond/update the drawing.  Hopefully getting this changed will save the next person a bit of turnaround time.

![image](https://user-images.githubusercontent.com/3662890/148808271-17b8adf8-4b2a-4982-bb95-cd9d74d59fc2.png)

**Comment by Trails5000** [comment]
design obsoleted, has been removed, somehow missed this issue
